name: CD - Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production   # optional: require approval
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI + bundles
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli databricks-bundles

      - name: Validate bundle (prod)
        run: databricks bundle validate -t prod

      - name: Deploy bundle to Prod
        run: databricks bundle deploy -t prod
