name: deploy-dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install latest Databricks CLI
        run: |
          pip install --upgrade pip
          pip install databricks-cli  # OLD one, skip this if not needed
          pip install databricks-sdk==0.19.0
          pip install databricks-bundles==0.19.0
          databricks --version

      - name: Configure Databricks Auth
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Validate Bundle
        run: databricks bundle validate -t dev

      - name: Deploy Bundle to Dev
        run: databricks bundle deploy -t dev
