name: deploy-dev

on:
  push:
    branches:
      - main   # run only when code is merged to main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install Databricks CLI + Bundles
      - name: Install Databricks CLI & Bundles
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli           # legacy CLI (optional, some projects still need it)
          pip install databricks-sdk==0.19.0   # SDK for bundle
          pip install databricks-bundles==0.266.0

      # 4. Validate bundle
      - name: Validate Databricks bundle
        run: databricks bundle validate -t dev

      # 5. Deploy to Databricks (Dev target)
      - name: Deploy bundle to Dev
        run: databricks bundle deploy -t dev

      # 6. Run bundle (if needed)
      - name: Run Databricks bundle
        run: databricks bundle run -t dev
