name: CI - Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI v2 (with bundle support)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          python -m pipx ensurepath
          pipx install databricks
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify CLI + Bundles
        run: |
          databricks -v
          databricks bundle -h   # ✅ bundle is part of CLI v2

      - name: Validate Databricks bundle (Dev)
        run: databricks bundle validate -t dev

      - name: Deploy Databricks bundle to Dev
        run: databricks bundle deploy -t dev
