name: CI - Deploy to Dev

on:
  push:
    branches:
      - main   # trigger on push to main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI + bundles
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli databricks-bundles

      - name: Validate bundle (dev)
        run: databricks bundle validate -t dev

      - name: Deploy bundle to Dev
        run: databricks bundle deploy -t dev
