name: Deploy to Prod
 
on:
  workflow_dispatch:
 
 
jobs:
  deploy_dev:
    name: "Deploy Databricks Bundle"
    runs-on: [ az, prod ]
    environment: prod
    defaults:
      run:
        working-directory: .
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
 
      - name: Set HOME variable
        run: echo "HOME=/home/github-runner" >> $GITHUB_ENV
 
      - name: Validate Databricks Bundle
        run: |
          echo "Starting Databricks Validation..."
          databricks bundle validate -t prod --debug
        env:
          DATABRICKS_HOST: 'https://adb-1952435459722444.4.azuredatabricks.net'
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID_PROD }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_PROD }}
          DATABRICKS_BUNDLE_ENV: prod
         
      - name: Deploy Databricks Bundle
        run: |
          echo "Starting Databricks Deployment..."
          databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: 'https://adb-1952435459722444.4.azuredatabricks.net'
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID_PROD }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_PROD }}
          DATABRICKS_BUNDLE_ENV: prod
